version: "3"
services: 
    www:
        build: .
        restart: always
        ports: 
            - '8000:80'
        volumes: 
            -  ./:/var/www/contaazul
        networks:
            - default
    db:
        image: mysql:5.7
        restart: always
        ports: 
            - '3306:3306'
        environment: 
            MYSQL_DATABASE: meudb
            MYSQL_USER: root
            MYSQL_PASSWORD: 
            MYSQL_ROOT_PASSWORD: 
            
volumes: 
    db_data: